name: Deploy Site

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    run: |
      curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/m-melis/unica-ml.github.io/dispatches --data '{"event_type": "build_application"}'